#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
wscript

Created by Johan Segolsson on 2012-03-08.
Copyright (c) 2012 Johan Segolsson. All rights reserved.
"""

import sys

def build( bld ):
	bld.stlib(
			target = 'scintilla',
			source = bld.path.ant_glob( [ '**/*.cxx', 'gtk/*.c' ] ),
			includes = [
					'..',
					'include',
					'src',
					'lexlib',
					'gtk',
				],
			export_includes = [
					'include',
				],
			use = 'GTK',
			install_path = None
		) # do not install this library

	bld.install_files('${PREFIX}/include/geany/scintilla', '''
			include/SciLexer.h
			include/Scintilla.h
			include/Scintilla.iface
			include/ScintillaWidget.h
		''')

	bld.install_as('${DOCDIR}/ScintillaLicense.txt', 'License.txt')

