#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
wscript

Created by Johan Segolsson on 2012-03-09.
Copyright (c) 2012 Johan Segolsson. All rights reserved.
"""

def build( bld ):
	icon_dest = '${DATADIR}/icons/hicolor/16x16/apps'
	start_dir = bld.path.find_dir('16x16')
	bld.install_files(icon_dest, start_dir.ant_glob('*.png'), cwd=start_dir)

	start_dir = bld.path.find_dir('48x48')
	icon_dest = '${DATADIR}/icons/hicolor/48x48/apps'
	bld.install_files(icon_dest, start_dir.ant_glob('*.png'), cwd=start_dir)

	start_dir = bld.path.find_dir('scalable')
	scalable_dest = '${DATADIR}/icons/hicolor/scalable/apps'
	bld.install_files(scalable_dest, start_dir.ant_glob('*.svg'), cwd=start_dir)
