#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
wscript

Created by Johan Segolsson on 2012-03-08.
Copyright (c) 2012 Johan Segolsson. All rights reserved.
"""

def build( bld ):
	_sources = [
			'about.c',
			'build.c',
			'callbacks.c',
			'dialogs.c',
			'document.c',
			'editor.c',
			'encodings.c',
			'filetypes.c',
			'geanyentryaction.c',
			'geanymenubuttonaction.c',
			'geanyobject.c',
			'geanywraplabel.c',
			'highlighting.c',
			'keybindings.c',
			'keyfile.c',
			'log.c',
			'main.c',
			'msgwindow.c',
			'navqueue.c',
			'notebook.c',
			'plugins.c',
			'pluginutils.c',
			'prefix.c',
			'prefs.c',
			'printing.c',
			'project.c',
			'sciwrappers.c',
			'search.c',
			'socket.c',
			'stash.c',
			'symbols.c',
			'templates.c',
			'toolbar.c',
			'tools.c',
			'sidebar.c',
			'vte.c',
			'ui_utils.c',
			'utils.c',
		]

	bld(
			name = 'core_inc',
			export_includes = '.',
		)

	# Since we link statically to libscintilla we need to compile this with
	# c++ even if we don't use c++ in this application.
	bld.program(
			features = [ 'c', 'cxx', 'cxxprogram' ],
			target = 'svi',
			source = _sources,
			includes = [
					'..',
					'.',
				],
			defines = ['G_LOG_DOMAIN="Geany"', 'GEANY_PRIVATE'],
			linkflags = ['-Wl,--export-dynamic'],
			use = [
					'GTK',
					'GLIB',
					'GIO',
					'GTHREAD',
					'SUNOS_SOCKET',

					'scintilla',
					'tagmanager',
					'mio',
				],
		)

	# Headers
	bld.install_files('${PREFIX}/include/geany', '''
			document.h
			editor.h
			encodings.h
			filetypes.h
			geany.h
			highlighting.h
			keybindings.h
			msgwindow.h
			plugindata.h
			prefs.h
			project.h
			search.h
			stash.h
			support.h
			templates.h
			toolbar.h
			ui_utils.h
			utils.h
			build.h
		''' )

