#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
src/wscript

Created by Johan Segolsson on 2012-03-08.
Copyright (c) 2012 Johan Segolsson. All rights reserved.
"""

def build(bld):
	bld.recurse( 'scintilla' )
	bld.recurse( 'tagmanager' )
	bld.recurse( 'core' )
	bld.recurse( 'plugins' )
