#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
wscript

Created by Johan Segolsson on 2012-03-09.
Copyright (c) 2012 Johan Segolsson. All rights reserved.
"""

def build( bld ):
	bld(
			source = 'geany.pc.in',
			dct = {
				'VERSION' : bld.env[ 'VERSION' ],
				'prefix': bld.env['PREFIX'],
				'exec_prefix': '${prefix}',
				'libdir': '${exec_prefix}/lib',
				'includedir': '${prefix}/include',
				'datarootdir': '${prefix}/share',
				'datadir': '${datarootdir}',
				'localedir': '${datarootdir}/locale'
			},
		)

	if bld.env['INTLTOOL']:
		bld(
				features = 'intltool_in',
				source = 'geany.desktop.in',
				podir='../po',
				flags = [ '-d', '-q', '-u', '-c' ],
				install_path = '${DATADIR}/applications'
			)

	bld(
			features = 'subst',
			source = 'geany.spec.in',
			target = 'geany.spec',
			install_path = None,
			dct = {'VERSION' : bld.env[ 'VERSION' ]},
		)
